version: "3.8"

services:

  mongodb-primary:
    image: mongo:7.0
    container_name: mongodb-primary
    hostname: mongodb-primary
    volumes:
      - ./data/mongodb-primary:/data/db
      - ./init/mongodb.conf:/etc/mongodb.conf
      - ./init/mongoinit.sh:/scripts/mongoinit.sh
    ports:
      - "27017:27017"
    command: ["mongod","--config","/etc/mongodb.conf"]
    networks:
      - mongo-cluster

  mongodb-secondary:
    image: mongo:7.0
    container_name: mongodb-secondary
    hostname: mongodb-secondary
    volumes:
      - ./data/mongodb-secondary:/data/db
      - ./init/mongodb.conf:/etc/mongodb.conf
    ports:
      - "27018:27017"
    command: ["mongod","--config","/etc/mongodb.conf"]
    networks:
      - mongo-cluster

  mongodb-arbiter:
    image: mongo:7.0
    container_name: mongodb-arbiter
    hostname: mongodb-arbiter
    volumes:
      - ./data/mongodb-arbiter:/data/db
      - ./init/mongodb.conf:/etc/mongodb.conf
    ports:
      - "27019:27017"
    command: ["mongod","--config","/etc/mongodb.conf"]
    networks:
      - mongo-cluster

networks:
  mongo-cluster:
    driver: bridge