version: '3.8'

services:
  postgresql:
    image: postgres:13.4
    container_name: postgresql
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: user
      TZ: "Asia/Tokyo"

