version: '3.8'

services:
  pgvector:
    image: pgvector/pgvector:0.8.0-pg17
    container_name: pgvector
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: user
      TZ: "Asia/Tokyo"
    volumes:
      - pgvector-data:/var/lib/postgresql/data

volumes:
  pgvector-data:
