services:
  postgres:
    image: postgres:16.15
    container_name: s4-postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: user
      POSTGRES_DB: test
      TZ: "Asia/Tokyo"

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.19.22
    container_name: s4-elasticsearch
    restart: always
    ports:
      - 9200:9200
    environment:
      discovery.type: single-node
      xpack.security.enabled: "false"
      ES_JAVA_OPTS: "-Xms512m -Xmx512m"
      TZ: "Asia/Tokyo"
