version: '3.8'

services:
  timescaledb:
    image: timescale/timescaledb:2.17.2-pg17
    container_name: timescaledb
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: user
      TZ: "Asia/Tokyo"
    volumes:
      - timescaledb-data:/var/lib/postgresql/data

volumes:
  timescaledb-data:
